version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates against the "ShortGPT-with-azure" branch
    target-branch: "ShortGPT-with-azure"
    # Labels on pull requests for version updates
    labels:
      - "docker"
      - "dependencies"
      - "security"

  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "ShortGPT-with-azure"
    labels:
      - "python"
      - "dependencies"
      - "security"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "ShortGPT-with-azure"
    labels:
      - "github-actions"
      - "dependencies"
      - "security"
